# Generated by Django 2.2.3 on 2019-07-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
