# Generated by Django 2.2.3 on 2019-07-14 05:59

from django.db import migrations


def create_currencies(apps, schema_editor):
    ExchangeRate = apps.get_model('scraper', 'ExchangeRate')
    currencies = [
        'USD', 'JPY', 'BGN', 'CZK', 'DKK', 'EEK', 'GBP', 'HUF', 'PLN', 'RON',
        'SEK', 'CHF', 'ISK', 'NOK', 'HRK', 'RUB', 'TRY', 'AUD', 'BRL', 'CAD',
        'CNY', 'HKD', 'IDR', 'INR', 'KRW', 'MXN', 'MYR', 'NZD', 'PHP', 'SGD',
        'THB', 'ZAR'
    ]
    currency_models = []
    for currency in currencies:
        currency_models.append(ExchangeRate(currency=currency))

    ExchangeRate.objects.bulk_create(currency_models)


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_currencies),
    ]
